### ISSUE TITLE
unable to access project files in UE 

### ISSUE THREAD

**Issue by giantmecha** [msp/6070-intro-to-metasounds#1]
hello! i can't seem to get this tutorial project to work. the project seems to open okay, but once in the editor I'm unable to access any of the files...basically all the metasound and patches folders are empty. I've tried on three machines (two PCs and one Mac) with no luck, so I don't *think* it's user error. thank you for any help!

**Comment by alx-s** [comment]
+1
(great videos though!)

**Comment by alx-s** [comment]
I have found a work around and have a guess on the issue.

**Work around:**
- online, in the github repo, select the uasset file you need, and download it (files have to be downloaded individually...)

![image](https://user-images.githubusercontent.com/3448675/217336409-0d376b1d-9306-4d45-908e-cbec6a6b6d4b.png)

-  on your computer, go in the folder of the unreal project, and replace the original uasset file with the one you just downloaded.

-  in unreal, the new uasset will appear automatically and work just fine.



**My guess at the issue:**
- The issue happened to me after downloading the zip file of the repo using google chrome (I didn't clone)
- Chrome gave me a caution message (files might be harmuful) but proceeded to downloading anyway
- The uasset files downloaded this way only weight 1Ko (rather than a couple hundread Ko!). They have for content something like::

![image](https://user-images.githubusercontent.com/3448675/217337966-886f8e2b-f027-4b14-9628-cf2d353e48f1.png)

I guess the issue has to do with Chrome download system


Hope it helps!

**Comment by msp** [comment]
I updated the README to detail cloning rather than downloading the project folder as the latter won't get all the LFS assets.
